tmsuser: s_ycba_imaging
#tmspw: ENV #prod
#tmspw: ENV #dev

tmshost: 172.18.56.252 #prod
#tmshost: 172.18.60.89 #dev

databaseName: TMS
harvesterLink: https://harvester-test.britishart.yale.edu/oaicatmuseum/OAIHandler?verb=GetRecord&identifier=oai:tms.ycba.yale.edu:{id}&metadataPrefix=lido
